### ISSUE TITLE
Rewrite to use a CSS grid

### ISSUE THREAD

**Issue by PoolloverNathan** [nomorenotes/nomorenotes#176]
**Is your feature request related to a problem? Please describe.**
The existing fixed-based UI is bad, and makes #34 hard.

**Describe the solution you'd like**
I would like to use a CSS grid instead of using `position: fixed`.

**Comment by PoolloverNathan** [comment]
hmm, yep
![image](https://github.com/nomorenotes/nomorenotes/assets/24194027/b7c45385-f722-4d69-b0dc-38462c0e9dea)

**Comment by PoolloverNathan** [comment]
![image](https://github.com/nomorenotes/nomorenotes/assets/24194027/360fa32f-a8d9-4ee8-95f8-3c996ac15cda)

**Comment by PoolloverNathan** [comment]
Excuse me?
![image](https://github.com/nomorenotes/nomorenotes/assets/24194027/51228180-9941-45eb-ba6b-fb4a6c0c4ffd)

**Comment by KUKHUA** [comment]
> Excuse me?

What this mean?
