### ISSUE TITLE
Create icons for apps.

### ISSUE THREAD

**Issue by PoolloverNathan** [nomorenotes/nomorenotes#258]
- [x] `appicons/chat.svg`]
  ![chat](/nomorenotes/nomorenotes/raw/258-create-icons-for-apps/appicons/chat.svg)
- [x] `appicons/upload.svg`]
  ![upload](/nomorenotes/nomorenotes/raw/258-create-icons-for-apps/appicons/upload.svg)
- [x] `appicons/upload-admin.svg`
  ![upload-admin](/nomorenotes/nomorenotes/raw/258-create-icons-for-apps/appicons/upload-admin.svg)
- [x] `appicons/vis.svg`
  ![vis](/nomorenotes/nomorenotes/raw/258-create-icons-for-apps/appicons/vis.svg)
- [x] `appicons/embed-recieve.svg`
  ![embed-recieve](/nomorenotes/nomorenotes/raw/258-create-icons-for-apps/appicons/embed-recieve.svg)

**Comment by KUKHUA** [comment]
We'll need to figure out what apps *to* make icons for.

**Comment by PoolloverNathan** [comment]
I'll go through the apps.

**Comment by PoolloverNathan** [comment]
@KUKHUA description updated

**Comment by KUKHUA** [comment]
k

**Comment by KUKHUA** [comment]
wonder what style I should go for...

**Comment by KUKHUA** [comment]
Wait.. what is "vis"?

**Comment by PoolloverNathan** [comment]
@KUKHUA It allows editing saveables (e.g. your name). It's intended for debugging, so it might be hidden.

**Comment by KUKHUA** [comment]
item

**Comment by KUKHUA** [comment]
Done.
